### ISSUE TITLE
Different answer formats spaced awkwardly on iOS10 (only)

### ISSUE THREAD

**Issue by ninoguba** [ResearchKit/ResearchKit#824]
This is the screenshot of the TextAnswerFormat on the iOS Simulator running iOS 10

![simulator screen shot sep 16 2016 10 00 24 am](https://cloud.githubusercontent.com/assets/4361804/18594431/dc7b507c-7bf4-11e6-8f99-b588f11f2b13.png)

**Comment by ninoguba** [comment]
These are the screenshots of the NumericAnswerFormat:

![simulator screen shot sep 16 2016 10 09 21 am](https://cloud.githubusercontent.com/assets/4361804/18594671/f2c6149c-7bf5-11e6-9af5-5ddfa8f5f2df.png)
![simulator screen shot sep 16 2016 10 09 15 am](https://cloud.githubusercontent.com/assets/4361804/18594669/f2c2c274-7bf5-11e6-8085-c074b4c4c0d8.png)
![simulator screen shot sep 16 2016 10 08 48 am](https://cloud.githubusercontent.com/assets/4361804/18594670/f2c54db4-7bf5-11e6-8da4-8c36dc89072d.png)

**Comment by ninoguba** [comment]
This is the screenshot of the ScaleAnswerFormat.  Seems ok but there are now wasted leading and training spaces.

![simulator screen shot sep 16 2016 10 12 52 am](https://cloud.githubusercontent.com/assets/4361804/18594790/8890cdd2-7bf6-11e6-8d70-9672934f8427.png)

**Comment by ninoguba** [comment]
This is the screenshot of a ValuePickerAnswerFormat.  The spacing is like before but the issue now is the global tint color is not respected for the text and detailText properties.

![simulator screen shot sep 16 2016 10 13 25 am](https://cloud.githubusercontent.com/assets/4361804/18594840/bfddcaa6-7bf6-11e6-84e6-5508f7c79cd9.png)

**Comment by Geosef** [comment]
This may have been addressed by pull request #806 which was in reference to issue #774 . Feel free to check those out for any help.

**Comment by ninoguba** [comment]
Thanks @Geosef! #806 indeed fixed the UI issues with numeric and scale answer formats on iOS 10. Hopefully this fix will be included in the stable branch soon.

So the only outstanding issue is the initial tint color of the text and detailText for choice answer format.

**Comment by ninoguba** [comment]
I have the following workaround to the selected textColor issue but wasn't sure this is how it is supposed to get fixed.

In ORKChoiceViewCell.m, I updated this:

```
- (void)updateSelectedItem {
    if (_immediateNavigation == NO) {
        self.accessoryView.hidden = _selectedItem ? NO : YES;

        // Added this to get the application's global tint color
        UIColor *globalTint = [[[UIApplication sharedApplication] delegate] window].tintColor;
        [self setTintColor:globalTint];

        self.shortLabel.textColor = _selectedItem ? [self tintColor] : [UIColor blackColor];
        self.longLabel.textColor = _selectedItem ? [[self tintColor] colorWithAlphaComponent:192.0 / 255.0] : [UIColor ork_darkGrayColor];
    }
}
```

**Comment by doreilly** [comment]
Unfortunately, #806 does not appear to completely address some of the rendering issues mentioned, and has negative impacts on other answer formats.

I have created a simple Swift 2.3 project to demonstrate errors I'm seeing and shared that at:
https://github.com/doreilly/ResearchKitLayoutBug

I took some screenshots in the iOS Simulator showing the before and after impacts of the commit both iOS 9.3 and iOS 10. They also exist in the repository linked above, but I've included them in the attached PDF.
[RK Render Errors.pdf](https://github.com/ResearchKit/ResearchKit/files/485962/RK.Render.Errors.pdf)

**Comment by ninoguba** [comment]
@doreilly not sure about your setup but i do have a project on Swift 2.3 now rendering completely fine on iOS with the PRs #806 , #821, and my fix above for the tint color of a text choice.  Thanks again @Geosef and @syoung-smallwisdom  for the fixes!

**Comment by doreilly** [comment]
@ninoguba I can't speak to the tint color, but I can say that PR #821 did not address all of my errors. Specifically, the an ORKQuestionStep with a Picker Answer format is still offset from its original vertical centering.

However, pulling the current master (ead0650dfbceb83fb20b92a82c4ce3bf14009ecd) AND reverting PR #806 appears to have solved all of my issues.

**Comment by map72** [comment]
The scale answer format is quite squished since I upgraded to xcode 8 - swift 2.3. This thread makes it sound like that issue was fixed when commit 806 was reverted but it is still squished for me.

**Comment by ninoguba** [comment]
I confirmed the layout issues for the following answer formats are fixed with the latest release (1.4):

- ORKTextAnswerFormat
- ORKNumericAnswerFormat
- ORKScaleAnswerFormat
- ORKTextChoiceAnswerFormat

But issues (old and new) remain for the following answer formats and steps:

- ORKCompletionStep (#820 and #864)
- ORKDateAnswerFormat 
- ORKTimeIntervalAnswerFormat
- ORKTimeOfDayAnswerFormat
- ORKValuePickerAnswerFormat

See screenshots taken from the ORKCatalog app running on iPhone 6 iOS 10.   All picker-type answer formats don't occupy the full width of the view.

![img_5557](https://cloud.githubusercontent.com/assets/4361804/20811213/b19bea20-b7c1-11e6-8f24-357009f7346d.png)
![img_5558](https://cloud.githubusercontent.com/assets/4361804/20811214/b19c9560-b7c1-11e6-9b0d-0e72ae850468.png)
![img_5556](https://cloud.githubusercontent.com/assets/4361804/20811216/b19ddba0-b7c1-11e6-8a97-5c0f29d2ec0d.png)
![img_5555](https://cloud.githubusercontent.com/assets/4361804/20811215/b19d07b6-b7c1-11e6-8de3-f0016f8b0ed7.png)

**Comment by ninoguba** [comment]
PR #831 fixes the issues with the picker-type formats and the completion step.  Once it is merged then we can finally close this one. Thanks!

**Comment by ninoguba** [comment]
Only the tintColor issue remains for the following:

- ORKTextChoiceAnswerFormat
- ORKBooleanAnswerFormat

As also reported on #874.

**Comment by umerkhan-apple** [comment]
Closing this issue as #874 is the only remaining one.
